import type { CarListItem } from './mapCarToRental';

/** Sample Car1_List payload when the live API returns no results. */
export const CAR_LIST_FALLBACK_RAW: CarListItem[] = [
  {
    VendorCode: 'AL',
    VehicleClassName: 'Mini',
    Category: 'Car',
    TransmissionType: 'Manual',
    VisitorsRate: 'AED 4959.00',
    RateAvailability: 'Available',
    Location: 'COUNTER IS IN TERMINAL - WALK TO CAR',
    VehicleMake: 'FORD KA OR SIMILAR',
    NumberOfDoors: '3',
    Seats: '4',
    BagCount: '1',
    PickupLocation: 'Dubai',
    ReturnLocation: 'Dubai',
    RowNum: 1,
    RateCode: 'AP1IE',
    RateToken: 'DEMO',
    TraceId: 'car-fallback-1'
  },
  {
    VendorCode: 'AL',
    VehicleClassName: 'Economy',
    Category: 'Car',
    TransmissionType: 'Automatic',
    VisitorsRate: 'AED 6804.58',
    RateAvailability: 'Available',
    Location: 'COUNTER IS IN TERMINAL - WALK TO CAR',
    VehicleMake: 'FORD FIESTA OR SIMILAR',
    NumberOfDoors: '3',
    Seats: '5',
    BagCount: '2',
    PickupLocation: 'Dubai',
    ReturnLocation: 'Dubai',
    RowNum: 2,
    RateCode: 'AP1IE',
    RateToken: 'DEMO',
    TraceId: 'car-fallback-2'
  },
  {
    VendorCode: 'ET',
    VehicleClassName: 'Compact',
    Category: 'Car',
    TransmissionType: 'Automatic',
    VisitorsRate: 'AED 9511.43',
    RateAvailability: 'Available',
    Location: 'COUNTER IS IN TERMINAL - WALK TO CAR',
    VehicleMake: 'OPEL ASTRA OR SIMILAR',
    NumberOfDoors: '5',
    Seats: '5',
    BagCount: '3',
    PickupLocation: 'Dubai',
    ReturnLocation: 'Dubai',
    RowNum: 3,
    RateCode: 'EE1IE',
    RateToken: 'DEMO',
    TraceId: 'car-fallback-3'
  },
  {
    VendorCode: 'ET',
    VehicleClassName: 'Premium',
    Category: 'Car',
    TransmissionType: 'Automatic',
    VisitorsRate: 'AED 18363.09',
    RateAvailability: 'Available',
    Location: 'COUNTER IS IN TERMINAL - WALK TO CAR',
    VehicleMake: 'AUDI A4 OR SIMILAR',
    NumberOfDoors: '4',
    Seats: '5',
    BagCount: '4',
    PickupLocation: 'Dubai',
    ReturnLocation: 'Dubai',
    RowNum: 4,
    RateCode: 'EE1IE',
    RateToken: 'DEMO',
    TraceId: 'car-fallback-4'
  },
  {
    VendorCode: 'ZL',
    VehicleClassName: 'Intermediate',
    Category: 'SUV',
    TransmissionType: 'Automatic',
    VisitorsRate: 'AED 22002.55',
    RateAvailability: 'Available',
    Location: 'COUNTER IS IN TERMINAL - WALK TO CAR',
    VehicleMake: 'NISSAN QASHQAI OR SIMILAR',
    NumberOfDoors: '5',
    Seats: '5',
    BagCount: '3',
    PickupLocation: 'Dubai',
    ReturnLocation: 'Dubai',
    RowNum: 5,
    RateCode: 'NP1IE',
    RateToken: 'DEMO',
    TraceId: 'car-fallback-5'
  },
  {
    VendorCode: 'ZL',
    VehicleClassName: 'Luxury',
    Category: 'Car',
    TransmissionType: 'Automatic',
    VisitorsRate: 'AED 29841.37',
    RateAvailability: 'Available',
    Location: 'COUNTER IS IN TERMINAL - WALK TO CAR',
    VehicleMake: 'BMW 5 SERIES OR SIMILAR',
    NumberOfDoors: '4',
    Seats: '5',
    BagCount: '4',
    PickupLocation: 'Dubai',
    ReturnLocation: 'Dubai',
    RowNum: 6,
    RateCode: 'NP1IE',
    RateToken: 'DEMO',
    TraceId: 'car-fallback-6'
  }
];
